---
abstract: 'A wrapper class for Face API of Microsoft Cognitive Services'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.4.1, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Microsoft-CognitiveServices-Face
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Net::Microsoft::CognitiveServices::Face:
    file: lib/Net/Microsoft/CognitiveServices/Face.pm
    version: '0.01'
  Net::Microsoft::CognitiveServices::Face::Base:
    file: lib/Net/Microsoft/CognitiveServices/Face/Base.pm
  Net::Microsoft::CognitiveServices::Face::Face:
    file: lib/Net/Microsoft/CognitiveServices/Face/Face.pm
  Net::Microsoft::CognitiveServices::Face::FaceList:
    file: lib/Net/Microsoft/CognitiveServices/Face/FaceList.pm
  Net::Microsoft::CognitiveServices::Face::Person:
    file: lib/Net/Microsoft/CognitiveServices/Face/Person.pm
  Net::Microsoft::CognitiveServices::Face::PersonGroup:
    file: lib/Net/Microsoft/CognitiveServices/Face/PersonGroup.pm
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/ytnobody/p5-Net-Microsoft-CognitiveServices-Face/issues
  homepage: https://github.com/ytnobody/p5-Net-Microsoft-CognitiveServices-Face
  repository: git://github.com/ytnobody/p5-Net-Microsoft-CognitiveServices-Face.git
version: '0.01'
